apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: vp-test
  region: us-west-1
managedNodeGroups:
  - name: metastore-mng
    labels: {role: metastore}
    instanceType: t3.large
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    volumeSize: 80
    privateNetworking: true
  - name: trino-mng
    labels: {role: trino}
    instanceType: t3.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 80
    privateNetworking: true
  - name: trino-worker-mng
    labels: {role: trino}
    instanceType: t3.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 80
    privateNetworking: true
