# Default values for vp-di-metastore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgres:
  name: metastore
  port: 5432

namespace:
  name: default
  
cluster:
  name: vp-test

metastore:
  name: metastore2
  nodegroupname: metastore-mng
  port: 9083
  image: scienz/walden-metastore:latest

trino:
  name: trino2
  port: 8080
  image: scienz/walden-trino:latest
  coordinator:
    name: trino2-coordinator
    nodegroupname: trino-mng
  headless:
    name: trino2-coordinator-headless
  worker:
    name: trino2-worker
    nodegroupname: trino-worker-mng

service:
  type: ClusterIP
  port: 80
