---
apiVersion: v1
kind: ConfigMap
metadata:
  name: properties-trino2
  namespace: default
data:
  node.properties.template: |
  {{ .Files.Get "node.properties.template" | indent 4 }}
  jvm.config: | 
  {{ .Files.Get "jvm.config" | indent 4 }}
  config.properties.template: | 
  {{ .Files.Get "config.properties.template" | indent 4 }}
  log.properties: |
  {{ .Files.Get "log.properties" | indent 4 }}
  hive.properties: |
  {{ .Files.Get "catalog/hive.properties" | indent 4 }}
  postgresql.properties: |
  {{ .Files.Get "catalog/postgresql.properties" | indent 4 }}
  thrift.properties: |
  {{ .Files.Get "catalog/thrift.properties" | indent 4 }}
  core-site.xml: |
  {{ .Files.Get "catalog/core-site.xml" | indent 4 }}