# Hive Metastore service, exposes port 9083 to other services (Presto /
# Alluxio)
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metastore.name }}
  name: {{ .Values.metastore.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.metastore.port }}
  selector:
    app: {{ .Values.metastore.name }}
status:
  loadBalancer: {}