# Hive standalone metastore, keeps track of table metadata.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.metastore.name }}
  name: {{ .Values.metastore.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metastore.name }}
  strategy: 
    rollingUpdate: 
      maxUnavailable: 20
  template:
    metadata:
      labels:
        app: {{ .Values.metastore.name }}
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        alpha.eksctl.io/cluster-name: {{ .Values.cluster.name }}
        alpha.eksctl.io/nodegroup-name: {{ .Values.metastore.nodegroupname }}
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Values.metastore.name }}
        image: {{ .Values.metastore.image }}
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: metatrino-secret
                key: rds-pg-host
          - name: POSTGRES_DBNAME
            valueFrom:
              secretKeyRef:
                name: metatrino-secret
                key: rds-pg-name
          - name: POSTGRES_PORT
            value: "{{ .Values.postgres.port }}"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: metatrino-secret
                key: rds-pg-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: metatrino-secret
                key: rds-pg-pass
          - name: METASTORE_NAME
            value: {{ .Values.metastore.name }}
          - name: METASTORE_PORT
            value: "{{ .Values.metastore.port }}"
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-vibrant-dragon
                key: id
          - name: S3_ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: s3-vibrant-dragon
                key: secret
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.metastore.port }}
        resources: {}
        volumeMounts:
          - mountPath: /apache-hive-metastore-3.1.2-bin/metastore-site.xml.template
            name: config
            subPath: metastore-site.xml.template
            readOnly: false
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: {{ .Values.metastore.name }}
      restartPolicy: Always
      serviceAccountName: ""
status: {}