apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metastore.name }}
  namespace: {{ .Values.namespace.name }}
data:
  metastore-site.xml.template: |-
{{ .Files.Get "configs/metastore-site.xml.template" | nindent 4 }}
