---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.trino.coordinator.name }}
  name: {{ .Values.trino.headless.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - name: "{{ .Values.trino.port }}"
    port: {{ .Values.trino.port }}
    targetPort: {{ .Values.trino.port }}
  selector:
    app: {{ .Values.trino.coordinator.name }}
status:
  loadBalancer: {}