---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.trino.coordinator.name }}
  name: {{ .Values.trino.coordinator.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  serviceName: "{{ .Values.trino.coordinator.name }}"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.trino.coordinator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.trino.coordinator.name }}
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        alpha.eksctl.io/cluster-name: {{ .Values.cluster.name }}
        alpha.eksctl.io/nodegroup-name: {{ .Values.trino.coordinator.nodegroupname }}
        role: trino
      volumes:
        - name: properties-vol
          configMap:
            name: properties-trino
        - name: pre-install
          emptyDir: {}
        - name: mem
          emptyDir:
            medium: "Memory"
            sizeLimit: 1G
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: copy-ro-scripts
        image: busybox
        command:
          - sh
          - -c
          - |
            cp /conf/node.properties.template /opt/trino/conf/ &&
            cp /conf/jvm.config /opt/trino/conf/ &&
            cp /conf/config.properties.template /opt/trino/conf/ &&
            mkdir -p /opt/trino/conf/catalog &&
            cp /conf/hive.properties /opt/trino/conf/catalog &&
            cp /conf/core-site.xml /opt/trino/conf/catalog &&
            sed -i "s#__S3_ACCESS_KEY_ID#$S3_ACCESS_KEY_ID#g"  /opt/trino/conf/catalog/core-site.xml &&
            sed -i "s#__S3_ACCESS_KEY_SECRET#$S3_ACCESS_KEY_SECRET#g"  /opt/trino/conf/catalog/core-site.xml &&
            sed -i "s#__S3_ACCESS_KEY_ID#$S3_ACCESS_KEY_ID#g"  /opt/trino/conf/catalog/hive.properties &&
            sed -i "s#__S3_ACCESS_KEY_SECRET#$S3_ACCESS_KEY_SECRET#g"  /opt/trino/conf/catalog/hive.properties &&
            echo 'connector.name=tpch' > /opt/trino/conf/catalog/tpch.properties
        volumeMounts:
          - name: properties-vol
            mountPath: /conf
          - name: pre-install
            mountPath: /opt/trino/conf
        env:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-vibrant-dragon
              key: id
        - name: S3_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-vibrant-dragon
              key: secret
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: HIVE_METASTORE_HOST
          value: {{ .Values.metastore.name }}
        - name: HIVE_METASTORE_PORT
          value: "{{ .Values.metastore.port }}"
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-vibrant-dragon
              key: id
        - name: S3_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-vibrant-dragon
              key: secret
        image: {{ .Values.trino.image }}
        imagePullPolicy: "Always"
        name: {{ .Values.trino.coordinator.name }}
        ports:
        - containerPort: {{ .Values.trino.port }}
        resources: {}
        volumeMounts:
          - name: pre-install
            mountPath: /trino-server-360/etc
      restartPolicy: Always
      serviceAccountName: ""