apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: vp-metatrino
  region: us-west-1
managedNodeGroups:
  - name: metastore-mng
    labels: {role: metastore}
    instanceType: t3.small
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    volumeSize: 10
    privateNetworking: true
    spot: true
  - name: trino-mng
    labels: {role: trino}
    instanceType: t3.small
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 10
    privateNetworking: true
    spot: true
