# Hive Metastore service, exposes port 9083 to other services (Presto /
# Alluxio)
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metastore2
  name: metastore2
  namespace: default
spec:
  ports:
  - port: 9083
  selector:
    app: metastore2
status:
  loadBalancer: {}