# Hive Metastore service, exposes port 9083 to other services (Presto /
# Alluxio)
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metastore2
  name: metastore2
  namespace: default
spec:
  ports:
  - port: 9083
  selector:
    app: metastore2
  template:
    spec: 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                - hive-instance
                #metastore-mng
              - key: alpha.eksctl.io/cluster-name
                operator: In
                values:
                - vp-test2
status:
  loadBalancer: {}