# Hive standalone metastore, keeps track of table metadata.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metastore2
  name: metastore2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metastore2
  strategy: {}
  template:
    metadata:
      labels:
        app: metastore2
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        alpha.eksctl.io/cluster-name: vp-metatrino
        alpha.eksctl.io/nodegroup-name: metastore-mng
      containers:
      - name: metastore
        image: scienz/walden-metastore:latest
        env:
          - name: POSTGRES_HOST
            value: {{ .Values.postgres.host }}
          - name: METASTORE_PORT
            value: "{{ .Values.metastore.port }}"
          - name: POSTGRES_USER
            value: {{ .Values.postgres.user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgres.pass }}
          - name: POSTGRES_PORT
            value: "{{ .Values.postgres.port }}"
          - name: METASTORE_DB
            value: {{ .Values.metastore.db }}
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.metastore.port }}
        resources: {}
        volumeMounts:
          - mountPath: /apache-hive-metastore-3.1.2-bin/metastore-site.xml.template
            name: config
            subPath: metastore-site.xml.template
            readOnly: false
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: metastore2
      restartPolicy: Always
      serviceAccountName: ""
status: {}