---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trino-coordinator
  name: trino-coordinator-headless
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: trino-coordinator
status:
  loadBalancer: {}