---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: trino2-worker
  name: trino2-worker
  namespace: default
spec:
  serviceName: "trino2-worker"
  replicas: 4
  selector:
    matchLabels:
      app: trino2-worker
  template:
    metadata:
      labels:
        app: trino2-worker
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        alpha.eksctl.io/cluster-name: vp-metatrino
        alpha.eksctl.io/nodegroup-name: trino-worker-mng
        role: trino
      volumes:
        - name: properties-vol
          configMap:
            name: properties-trino2
        - name: pre-install
          emptyDir: {}
        - name: mem
          emptyDir:
            medium: "Memory"
            sizeLimit: 1G
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: copy-ro-scripts
        image: busybox
        command:
          - sh
          - -c
          - |
            cp /conf/node.properties.template /opt/trino/conf/ &&
            cp /conf/jvm.config /opt/trino/conf/ &&
            cp /conf/config.properties.template /opt/trino/conf/ &&
            mkdir -p /opt/trino/conf/catalog &&
            cp /conf/hive.properties /opt/trino/conf/catalog &&
            cp /conf/tiledb.properties /opt/trino/conf/catalog &&
            cp /conf/core-site.xml /opt/trino/conf/catalog &&
            sed -i "s#__S3_ACCESS_KEY_ID#$S3_ACCESS_KEY_ID#g"  /opt/trino/conf/catalog/core-site.xml &&
            sed -i "s#__S3_ACCESS_KEY_SECRET#$S3_ACCESS_KEY_SECRET#g"  /opt/trino/conf/catalog/core-site.xml &&
            sed -i "s#__S3_ACCESS_KEY_ID#$S3_ACCESS_KEY_ID#g"  /opt/trino/conf/catalog/hive.properties &&
            sed -i "s#__S3_ACCESS_KEY_SECRET#$S3_ACCESS_KEY_SECRET#g"  /opt/trino/conf/catalog/hive.properties &&
            sed -i "s#__S3_ACCESS_KEY_ID#$S3_ACCESS_KEY_ID#g"  /opt/trino/conf/catalog/tiledb.properties &&
            sed -i "s#__S3_ACCESS_KEY_SECRET#$S3_ACCESS_KEY_SECRET#g"  /opt/trino/conf/catalog/tiledb.properties &&
            echo 'connector.name=tpch' > /opt/trino/conf/catalog/tpch.properties
        volumeMounts:
          - name: properties-vol
            mountPath: /conf
          - name: pre-install
            mountPath: /opt/trino/conf
        env:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-vibrant-dragon
              key: id
        - name: S3_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-vibrant-dragon
              key: secret
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: HIVE_METASTORE_HOST
          value: metastore2
        - name: HIVE_METASTORE_PORT
          value: "9083"
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-vibrant-dragon
              key: id
        - name: S3_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: s3-vibrant-dragon
              key: secret
        image: scienz/walden-trino:latest
        imagePullPolicy: "Always"
        name: trino-worker
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
          - name: pre-install
            mountPath: /trino-server-356/etc
      restartPolicy: Always
      serviceAccountName: ""